### ISSUE TITLE
library not found

### ISSUE THREAD

**Issue by botmane** [amplitude/GTM-iOS-Demo#1]
Hello,

When trying to run this demo app, I get the following error:
![image](https://cloud.githubusercontent.com/assets/6231769/15716954/111eb23e-2825-11e6-8aa5-d49048966ab8.png)

I hope this bug will be corrected soon.

Regards,

**Comment by djih** [comment]
@botmane sorry about that. This app expects you to install our SDK via Cocoapods. If you have it installed, all you need to do is run `pod install` in the base directory, and it is configured to load our library for you. If you don't want to use Cocoapods, you can follow the [setup instructions](https://github.com/amplitude/amplitude-ios#setup) steps 2-4. I will update the Readme to explain that. Hope that helps
